// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteDevice(arg1) {
  return window['go']['main']['App']['DeleteDevice'](arg1);
}

export function DiscoverBulbs() {
  return window['go']['main']['App']['DiscoverBulbs']();
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetIsPlaying() {
  return window['go']['main']['App']['GetIsPlaying']();
}

export function NewBasicDevice(arg1, arg2) {
  return window['go']['main']['App']['NewBasicDevice'](arg1, arg2);
}

export function NewFullDevice(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['NewFullDevice'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}
