// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteDevice(arg1:string):Promise<void>;

export function DiscoverBulbs():Promise<boolean>;

export function GetDevices():Promise<Array<main.Device>>;

export function NewBasicDevice(arg1:string,arg2:string):Promise<main.Device>;

export function NewFullDevice(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:Array<string>,arg7:boolean):Promise<main.Device>;
